changelog:
  exclude:
    authors:
      - github-actions[bot]
  categories:
    - title: 新功能
      labels:
        - feature
        - enhancement
    - title: 修复
      labels:
        - fix
        - bug
    - title: 文档与工程
      labels:
        - docs
        - chore
        - ci
    - title: 其他更新
      labels:
        - "*"
